name: Run Antithesis Test

on: 
  #manual run
  workflow_dispatch:
    inputs:
      duration:
        type: string
        required: true
        default: '15'
        description: Duration to the test run
      emails:
        type: string
        required: true
        description: Email receipents

jobs:
  manual_run:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: antithesishq/antithesis-trigger-action@main
        with:
          notebook_name: ps_demo
          tenant: demo
          username: ${{ secrets.ANTITHESIS_USER_NAME }}
          password: ${{ secrets.ANTITHESIS_PASSWORD }}
          github_token: ${{ secrets.GH_PAT }}
          images:  ray:symbols;ray-client:latest
          config_image: ray-config:latest
          email_recipients: ${{ github.event.inputs.emails }}
          description: "[${{ github.repository }}] CI for ${{ github.ref_name }} (commit ${{ github.sha }})"
          additional_parameters: |-
            antithesis.duration=${{ github.event.inputs.duration }}
